homework: lesson-23 Kanstantsin Tarhashyn
anrers/WD15-onl pull request #115
Opened 2024-10-27 20:40 UTC by yuntor00

2024-10-28 14:46 UTC, anrers requested changes

2024-10-28 14:46 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_23/task1.php
> +    ){}
https://www.php-fig.org/per/coding-style/#44-methods-and-functions

2024-10-28 14:46 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_23/task1.php
> +        $index = array_search($permission, $this->permissions, true);
У permission есть id, если в свойстве $this->permissions использовать id как ключ массива, то можно упростить код

2024-10-28 17:41 UTC, yuntor00 commented on homeworks/Kanstantsin_Tarhashyn/lesson_23/task1.php
> +    ){}
Понял, зафиксил

2024-11-04 14:52 UTC, anrers approved these changes

2024-11-04 14:52 UTC, merged