homework: lesson-25 Vladimir Moskaluk
anrers/WD15-onl pull request #121
Opened 2024-10-30 21:34 UTC by DerecCross

2024-10-31 15:23 UTC, anrers requested changes

2024-10-31 15:23 UTC, anrers commented on homeworks/vladimir_moskaluk/lesson_25/task_1/src/Cart.php
> +        $this->items[] = $product;
Если добавлять под каким-нибудь уникальным ключом, то можно упростить логику во всех методах. Добавь свойство id к товару и измени логику более простую

2024-10-31 15:23 UTC, anrers commented on homeworks/vladimir_moskaluk/lesson_25/task_2/src/Library.php
> +        $this->books[] = $book;
так же как и для заказа, можно упростить

2024-11-10 22:04 UTC, DerecCross commented on homeworks/vladimir_moskaluk/lesson_25/task_1/src/Cart.php
> +        $this->items[] = $product;
Переделано с учетом сделанных замечаний

2024-11-11 15:06 UTC, anrers approved these changes

2024-11-11 15:06 UTC, merged