homework: lesson-24 Kanstantsin Tarhashyn
anrers/WD15-onl pull request #123
Opened 2024-10-30 22:08 UTC by yuntor00

2024-10-31 15:14 UTC, anrers requested changes

2024-10-31 15:14 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_24/task1/Invoice.php
> +    public function __construct($invoiceId, $customer, AbstactProduct $product)
если свойства типизированы,  то параметры конструктора тоже нужно типизировать. И лучше использовать сокращенный синтаксим

2024-10-31 17:20 UTC, yuntor00 commented on homeworks/Kanstantsin_Tarhashyn/lesson_24/task1/Invoice.php
> +        $this->products[] = ['product' => $product, 'quantity' => $quantity];
Понял, зафиксил

2024-10-31 17:20 UTC, yuntor00 commented on homeworks/Kanstantsin_Tarhashyn/lesson_24/task1/Invoice.php
> +    public function __construct($invoiceId, $customer, AbstactProduct $product)
Понял, зафиксил

2024-11-11 15:10 UTC, anrers requested changes

2024-11-11 15:10 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_24/task1/Order.php
> +    public function __construct($orderId, AbstactProduct $product, $quantity)
типизация

2024-11-11 15:10 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_24/task1/AbstractProduct.php
> +    public function __construct($id, $name, $price)
типизация, в наследнике добавил типы, значит и тут должны быть

2024-11-11 15:10 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_24/task1/AbstractProduct.php
> +    protected $id;
типизация, в наследнике добавил типы, значит и тут должны быть

2024-11-11 15:10 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_24/task2/TextDocument.php
> +    public function __construct($title, $description, $wordCount)
типизация

2024-11-11 15:10 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_24/task2/VideoDocument.php
> +    public function __construct($title, $description, $duration)
типизация

2024-11-14 14:28 UTC, merged