homework: lesson-25 Kanstantsin Tarhashyn
anrers/WD15-onl pull request #131
Opened 2024-11-03 22:17 UTC by yuntor00

2024-11-04 14:48 UTC, anrers requested changes

2024-11-04 14:48 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_25/task1/Cart.php
> +        foreach ($this->products as $existingProduct) {
проверить существование возможно при помощи  $this->products[$product->getName()], без перебора всего массива

2024-11-04 14:48 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_25/task1/Cart.php
> +            if ($product->getName() === $productName)
продукт можно получить при помощи $this->products[$product->getName()], без перебора всего массива

2024-11-04 14:48 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_25/task2/Library.php
> +        $this->books[] = $book;
Добавь объекту книги id и используй его как ключ. упрости метод removeBook

2024-11-04 14:48 UTC, anrers commented on homeworks/Kanstantsin_Tarhashyn/lesson_25/task1/Cart.php
> +        {
https://www.php-fig.org/per/coding-style/#55-foreach проверь стили во всех методах

2024-11-04 19:18 UTC, yuntor00 commented on homeworks/Kanstantsin_Tarhashyn/lesson_25/task1/Cart.php
> +        foreach ($this->products as $existingProduct) {
Понял, зафиксил

2024-11-04 19:18 UTC, yuntor00 commented on homeworks/Kanstantsin_Tarhashyn/lesson_25/task1/Cart.php
> +            if ($product->getName() === $productName)
Понял, зафиксил

2024-11-04 19:18 UTC, yuntor00 commented on homeworks/Kanstantsin_Tarhashyn/lesson_25/task2/Library.php
> +        $this->books[] = $book;
Понял, зафиксил

2024-11-04 19:18 UTC, yuntor00 commented on homeworks/Kanstantsin_Tarhashyn/lesson_25/task1/Cart.php
> +        {
Понял, зафиксил

2024-11-14 14:31 UTC, anrers approved these changes

2024-11-14 14:31 UTC, merged