homework: lesson-28 Kirill Tim
anrers/WD15-onl pull request #137
Opened 2024-11-10 15:03 UTC by KirTimohovich

2024-11-14 15:03 UTC, anrers requested changes

2024-11-14 15:03 UTC, anrers commented on homeworks/Kir_Tim/lesson_28/db_enrollments.php
> +    SELECT students.ID FROM students, enrollments WHERE enrollments.STUDENTS_ID <> students.ID; // В таблице должна быть хотя бы одна запись со STUDENTS_ID
у этого запроса может быть не корректное поведение. Сделай более надёжный запрос для получения юзеров

2024-11-14 15:03 UTC, anrers commented on homeworks/Kir_Tim/lesson_28/db_enrollments.php
> +    foreach ($ID as $stId) {
можно добавить всех и 1 запросом. Изучить как можно передавать несколько групп в values

2024-11-24 09:52 UTC, KirTimohovich commented on homeworks/Kir_Tim/lesson_28/db_enrollments.php
> +    SELECT students.ID FROM students, enrollments WHERE enrollments.STUDENTS_ID <> students.ID; // В таблице должна быть хотя бы одна запись со STUDENTS_ID
Исправлено

2024-11-24 09:52 UTC, KirTimohovich commented on homeworks/Kir_Tim/lesson_28/db_enrollments.php
> +    foreach ($ID as $stId) {
Пока не придумал решения лучше =))

2024-12-05 14:00 UTC, anrers commented on homeworks/Kir_Tim/lesson_28/db_enrollments.php
> +    SELECT students.ID FROM students, enrollments WHERE enrollments.STUDENTS_ID <> students.ID; // В таблице должна быть хотя бы одна запись со STUDENTS_ID
ID в таблице students == ID в таблице enrollments? или NATURAL JOIN понимает, что id в students  == полю STUDENTS_ID в таблице enrollments?

2025-02-10 08:33 UTC, anrers approved these changes

2025-02-10 08:33 UTC, merged