homework: lesson-21 Alex Moroz
anrers/WD15-onl pull request #90
Opened 2024-10-16 23:28 UTC by Aliaksandra94

2024-10-17 11:30 UTC, anrers requested changes

2024-10-17 11:30 UTC, anrers commented on homeworks/alex_moroz/lesson_21/hw.php
> +<?php $isFormedFilledCorrectly = isset($_GET['success']) ?? $_GET['success'] === true;
почему используется ?? ?

2024-10-17 11:30 UTC, anrers commented on homeworks/alex_moroz/lesson_21/src/implode.php
> +function mapped_implode2($array, $separator = ', ', $innerSeparator = ': '): string
mapped_implode2 такое название не даёт понимания чем функция отличается от mapped_implode и что она делает

2024-10-17 12:03 UTC, Aliaksandra94 commented on homeworks/alex_moroz/lesson_21/src/implode.php
> +function mapped_implode2($array, $separator = ', ', $innerSeparator = ': '): string
Функции выполняют одну логику: был вопрос какой подход предпочтительней использовать. В ПР оставила, чтобы не забыть про вопрос)

2024-10-17 12:46 UTC, Aliaksandra94 commented on homeworks/alex_moroz/lesson_21/hw.php
> +<?php $isFormedFilledCorrectly = isset($_GET['success']) ?? $_GET['success'] === true;
Спасибо, исправила

Не знаю, ретроградный меркурий, бес попутал, может полнолуние, но скорее всего потому что невнимательна 🤦

2024-10-21 15:02 UTC, anrers approved these changes

2024-10-21 15:02 UTC, merged